services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tech_app
    environment:
      DJANGO_SETTINGS_MODULE: "core.settings"
      POSTGRES_DB: "tech_db"
      POSTGRES_USER: "tech_user"
      POSTGRES_PASSWORD: "tech_pass"
      POSTGRES_HOST: "postgres_tech"
      POSTGRES_PORT: "5432"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8001:8001"
    depends_on:
      - postgres_tech

  postgres_tech:
    image: postgres:15
    container_name: postgres_tech
    restart: always
    environment:
      POSTGRES_DB: tech_db
      POSTGRES_USER: tech_user
      POSTGRES_PASSWORD: tech_pass
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

