services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tech_app
    environment:
      DJANGO_SETTINGS_MODULE: "core.settings"
      POSTGRES_DB: "tech_db"
      POSTGRES_USER: "tech_user"
      POSTGRES_PASSWORD: "tech_pass"
      POSTGRES_HOST: "postgres_tech"
      POSTGRES_PORT: "5432"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8001:8001"
    depends_on:
      - postgres_tech

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "sleep 5 && certbot certonly --non-interactive --webroot -w /var/www/certbot --email gashiykh@bk.ru --agree-tos --no-eff-email -d platform.technowomen.kz"

  postgres_tech:
    image: postgres:15
    container_name: postgres_tech
    restart: always
    environment:
      POSTGRES_DB: tech_db
      POSTGRES_USER: tech_user
      POSTGRES_PASSWORD: tech_pass
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  certbot-etc:
  certbot-var:
  postgres_data:

